import type { BadgeTone } from '@/components/ui/Badge'
import type { TimelineEventType } from './types'

/** Label, icon, and palette tone for every timeline event category. Shared by
 *  the timeline view and the add-event dialog so the two never drift. */
export const TIMELINE_META: Record<TimelineEventType, { label: string; icon: string; tone: BadgeTone }> = {
  joined: { label: 'Joined', icon: 'UserPlus', tone: 'emerald' },
  promoted: { label: 'Promoted', icon: 'TrendingUp', tone: 'indigo' },
  transferred: { label: 'Transferred', icon: 'ArrowLeftRight', tone: 'blue' },
  meeting: { label: 'Meeting', icon: 'Users', tone: 'teal' },
  call: { label: 'Phone Call', icon: 'PhoneCall', tone: 'teal' },
  email: { label: 'Email', icon: 'Mail', tone: 'indigo' },
  whatsapp: { label: 'WhatsApp', icon: 'MessageCircle', tone: 'emerald' },
  followup: { label: 'Follow-up', icon: 'CalendarClock', tone: 'amber' },
  note: { label: 'Note Added', icon: 'StickyNote', tone: 'neutral' },
  document: { label: 'Document Uploaded', icon: 'FileText', tone: 'purple' },
  custom: { label: 'Custom', icon: 'Sparkles', tone: 'gray' },
}

/** Categories a user can add by hand (system-only kinds like `joined` and
 *  `transferred` are generated by the app). */
export const MANUAL_EVENT_TYPES: TimelineEventType[] = [
  'meeting', 'call', 'email', 'whatsapp', 'followup', 'note', 'document', 'promoted', 'custom',
]
