import type { BadgeTone } from '@/components/ui/Badge'
import type { TimelineEvent, TimelineEventType } from './types'

/** Label, icon, and palette tone for every timeline event category. Shared by
 *  the timeline view and the add-event dialog so the two never drift. */
export const TIMELINE_META: Record<TimelineEventType, { label: string; icon: string; tone: BadgeTone }> = {
  joined: { label: 'Joined', icon: 'UserPlus', tone: 'emerald' },
  promoted: { label: 'Promoted', icon: 'TrendingUp', tone: 'indigo' },
  transferred: { label: 'Transferred', icon: 'ArrowLeftRight', tone: 'blue' },
  meeting: { label: 'Meeting', icon: 'Users', tone: 'teal' },
  inPerson: { label: 'In Person', icon: 'Handshake', tone: 'teal' },
  call: { label: 'Phone Call', icon: 'PhoneCall', tone: 'teal' },
  email: { label: 'Email', icon: 'Mail', tone: 'indigo' },
  whatsapp: { label: 'WhatsApp', icon: 'MessageCircle', tone: 'emerald' },
  followup: { label: 'Follow-up', icon: 'CalendarClock', tone: 'amber' },
  note: { label: 'Note Added', icon: 'StickyNote', tone: 'neutral' },
  document: { label: 'Document Uploaded', icon: 'FileText', tone: 'purple' },
  custom: { label: 'Custom', icon: 'Sparkles', tone: 'gray' },
}

/** Categories a user can add by hand (system-only kinds like `joined` and
 *  `transferred` are generated by the app). */
export const MANUAL_EVENT_TYPES: TimelineEventType[] = [
  'inPerson', 'call', 'email', 'whatsapp', 'followup', 'note', 'document', 'promoted', 'custom',
]

/** Every manually-loggable type including `meeting`, `meeting` listed first
 *  so it's the default selection — used by the single "Add Activity" entry
 *  point, which offers the complete type list rather than a curated subset. */
export const ALL_EVENT_TYPES: TimelineEventType[] = ['meeting', ...MANUAL_EVENT_TYPES]

/** The subset of `MANUAL_EVENT_TYPES` (plus `meeting`) that are actually
 *  forms of meeting/contact with a person — used to log an entry against a
 *  specific employee without offering unrelated categories like
 *  Note/Document/Promoted in the same dropdown. `meeting` is appended last
 *  to preserve `inPerson` as this flow's existing default type. */
export const MEETING_LOG_TYPES: TimelineEventType[] = [
  'inPerson', 'call', 'email', 'whatsapp', 'followup', 'custom', 'meeting',
]

/** Badge text for a timeline entry — a `custom` entry shows the user's own
 *  label instead of the generic "Custom" category name when one was given. */
export function timelineEventLabel(e: Pick<TimelineEvent, 'type' | 'customLabel'>) {
  return e.type === 'custom' && e.customLabel ? e.customLabel : TIMELINE_META[e.type].label
}
