export type Domain = 'geo' | 'org'
export type Status = 'active' | 'archived'

export interface NodeType {
  key: string
  domain: Domain
  label: string
  icon: string
  /** allowed child type keys; empty = any */
  childKeys: string[]
  level: number
}

export interface HierNode {
  id: string
  domain: Domain
  typeKey: string
  parentId: string | null
  /** state LGD code this node belongs under (org nodes are jurisdictioned to a state) */
  stateCode: number | null
  name: string
  code: string | null
  sortOrder: number
  metadata: Record<string, string>
  status: Status
}

export type RelationshipStatus = 'engaged' | 'developing' | 'dormant' | 'new'
/** Five-point relationship quality scale. */
export type RelationshipQuality = 'excellent' | 'good' | 'neutral' | 'weak' | 'poor'
export type PreferredComm = 'phone' | 'email' | 'whatsapp' | 'in-person' | 'sms'

/** Timeline event categories. `source: 'system'` events (transfers, joins) are
 *  generated by the app and can't be hand-edited; the rest are added manually. */
export type TimelineEventType =
  | 'joined' | 'promoted' | 'transferred' | 'meeting' | 'inPerson' | 'call' | 'email'
  | 'whatsapp' | 'followup' | 'note' | 'document' | 'custom'

export interface TimelineEvent {
  id: string
  employeeId: string
  type: TimelineEventType
  title: string
  /** User-supplied name for the category, shown instead of the generic
   *  "Custom" badge text. Only meaningful when `type === 'custom'`. */
  customLabel?: string
  /** ISO date (YYYY-MM-DD) the event happened on. */
  date: string
  /** Optional time of day (HH:MM), alongside `date`. */
  time?: string
  note: string
  source: 'manual' | 'system'
  /** Names of AMNEX sales team members who attended this event. */
  attendees?: string[]
  /** Whether the meeting/interaction actually happened. `undefined` = not
   *  marked either way (the default for every new entry). */
  attended?: boolean
}

/** An immutable record of a posting change. A transfer both mutates the
 *  employee's live posting and appends a `transferred` timeline event. */
export interface Transfer {
  id: string
  employeeId: string
  fromDesignation: string
  toDesignation: string
  fromDepartmentName: string
  toDepartmentName: string
  fromOfficeName: string
  toOfficeName: string
  /** New posting node the employee moves under. */
  toOrgNodeId: string
  /** Reporting manager before/after the transfer — '—' when there wasn't one. */
  fromManagerName: string
  toManagerName: string
  effectiveDate: string
  reason: string
  remarks: string
}

/** Acting or Additional charge — a position an employee holds beyond their
 *  substantive posting. `acting` is temporary (has an end date); `additional`
 *  is a concurrently-held posting. */
export interface Charge {
  id: string
  kind: 'acting' | 'additional'
  title: string
  /** Optional org node the charge is attached to. */
  orgNodeId: string | null
  startDate: string | null
  endDate: string | null
  reason: string
}

export interface Employee {
  id: string
  code: string
  name: string
  designation: string
  email: string
  phone: string
  /** Organization/company name — from a visiting card, when the contact
   *  isn't a direct government employee (e.g. a vendor or consultant). */
  company: string
  address: string
  website: string
  photoUrl: string | null
  orgNodeId: string
  managerId: string | null
  /** A vacant position is a real seat in the hierarchy with a title but no
   *  incumbent yet. It renders distinctly and can be filled later ("assign a
   *  person") without rebuilding the tree. */
  vacant: boolean
  /** Whether this person is tracked as a relationship contact. When false,
   *  the fields below are hidden in the UI but kept intact so re-enabling
   *  restores them. */
  connected: boolean
  relationshipStatus: RelationshipStatus
  relationshipQuality: RelationshipQuality
  relationshipType: string
  introducedBy: string
  /** Flagged as a high-priority / VIP contact. */
  importantContact: boolean
  /** A contact can have more than one preferred channel. */
  preferredComm: PreferredComm[]
  lastInteractionAt: string | null
  followUpDate: string | null
  notes: string
  /** Acting + additional charges this person concurrently holds. */
  charges: Charge[]
  /** User-uploaded visiting cards. Each card holds a front image/PDF and an
   *  optional back, stored as data URLs. A person can have several cards. */
  visitingCards: VisitingCardItem[]
  metadata: Record<string, string>
  status: Status
}

/** A single sales opportunity/work item a department is pursuing or executing.
 *  Stored JSON-serialized in the department node's `metadata.works`, so the
 *  generic HierNode shape stays unchanged. */
export interface DepartmentWork {
  id: string
  opportunityName: string
  /** GEM bid number or tender ID, whichever applies. */
  gemTenderId: string
  /** ISO date (YYYY-MM-DD) the tender/GEM listing was published. */
  publishDate: string
  /** ISO date (YYYY-MM-DD) the bid is due. */
  submissionDate: string
  vertical: string
  /** One or more component/product-line tags. A work saved before this field
   *  became a multiselect may have a legacy single string here on disk —
   *  `parseWorks` (department-meta.ts) migrates it to a one-item array on read. */
  component: string[]
  quantity: string
  /** ISO 4217 code the value/EMD amounts below are denominated in — see
   *  `WORK_CURRENCIES`. */
  currency: string
  /** Raw number the user entered, scaled by `valueUnit`. */
  valueAmount: string
  /** Scale `valueAmount` is expressed in — see `WORK_VALUE_UNITS`. */
  valueUnit: string
  /** Whether the opportunity's budget figure is confirmed. `''` = not yet
   *  answered, so existing works don't force a choice. */
  budgetKnown: string
  /** EMD amount stated in the tender, scaled by `emdUnit` — the value field
   *  is disabled once the budget isn't confirmed, and this is used instead to
   *  derive a budget range (see `estimateBudgetRangeFromEmd`). */
  emdAmount: string
  emdUnit: string
  /** AMNEX sales-team member's email who owns this specific opportunity — same
   *  convention as `Employee.metadata.relationshipOwner` / a department's
   *  `metadata.salesGeo`. Empty string when unset (including on works parsed
   *  from data saved before this field existed). */
  salesPersonEmail: string
}

/** One visiting card: a required front and an optional back, each an image or
 *  PDF stored as a data URL with its original filename. */
export interface VisitingCardItem {
  id: string
  frontUrl: string
  frontName: string
  backUrl: string | null
  backName: string | null
}

export interface ExternalId {
  entityType: 'geo_node' | 'org_node' | 'employee'
  entityId: string
  system: string
  value: string
}

export interface SearchResult {
  /** Navigation discriminant only. 'node'/'employee' route via the existing
   *  ws.select() workspace-selection mechanism; 'other' routes via the
   *  owning category's `path()` instead (see search-categories.ts). Adding a
   *  new entity type never adds a new value here — it's 'other' unless it's
   *  literally backed by HierNode or Employee. */
  kind: 'node' | 'employee' | 'other'
  /** Open string key into SEARCH_CATEGORIES (search-categories.ts) — not a
   *  closed union, same "data not enum" convention as HierNode.typeKey. */
  category: string
  id: string
  title: string
  subtitle: string
  code: string | null
  domain: Domain | null
  stateCode: number | null
  /** Short reason the result matched, shown by natural-language search. */
  note?: string
  /** For a `kind: 'other'` result that isn't independently addressable — the
   *  HierNode id its `path()` should navigate to instead (e.g. a Work's
   *  owning department). Omitted for results that don't need it. */
  containerId?: string
}

export interface FieldDef {
  key: string
  label: string
  type: 'string' | 'text' | 'url' | 'email' | 'phone'
}
