/** Three hierarchies over one node engine. `'sales'` carries AMNEX coverage
 *  areas (Zone/Region/Cluster/…); its NODE_TYPES rows arrive with the
 *  Coverage phase, so today the value is admitted but unused. */
export type Domain = 'geo' | 'org' | 'sales'
export type Status = 'active' | 'archived'

export interface NodeType {
  key: string
  domain: Domain
  label: string
  icon: string
  /** allowed child type keys; empty = any */
  childKeys: string[]
  level: number
}

export interface HierNode {
  id: string
  domain: Domain
  typeKey: string
  parentId: string | null
  /** state LGD code this node belongs under (org nodes are jurisdictioned to a state) */
  stateCode: number | null
  name: string
  code: string | null
  sortOrder: number
  metadata: Record<string, string>
  status: Status
}

export type RelationshipStatus = 'engaged' | 'developing' | 'dormant' | 'new'
/** Five-point relationship quality scale. */
export type RelationshipQuality = 'excellent' | 'good' | 'neutral' | 'weak' | 'poor'
export type PreferredComm = 'phone' | 'email' | 'whatsapp' | 'in-person' | 'sms'

/** Timeline event categories. `source: 'system'` events (transfers, joins) are
 *  generated by the app and can't be hand-edited; the rest are added manually. */
export type TimelineEventType =
  | 'joined' | 'promoted' | 'transferred' | 'meeting' | 'inPerson' | 'call' | 'email'
  | 'whatsapp' | 'followup' | 'note' | 'document' | 'custom'

export interface TimelineEvent {
  id: string
  employeeId: string
  type: TimelineEventType
  title: string
  /** User-supplied name for the category, shown instead of the generic
   *  "Custom" badge text. Only meaningful when `type === 'custom'`. */
  customLabel?: string
  /** ISO date (YYYY-MM-DD) the event happened on. */
  date: string
  /** Optional time of day (HH:MM), alongside `date`. */
  time?: string
  note: string
  source: 'manual' | 'system'
  /** Names of AMNEX sales team members who attended this event. */
  attendees?: string[]
  /** Whether the meeting/interaction actually happened. `undefined` = not
   *  marked either way (the default for every new entry). */
  attended?: boolean
}

/** An immutable record of a posting change. A transfer both mutates the
 *  employee's live posting and appends a `transferred` timeline event. */
export interface Transfer {
  id: string
  employeeId: string
  fromDesignation: string
  toDesignation: string
  fromDepartmentName: string
  toDepartmentName: string
  fromOfficeName: string
  toOfficeName: string
  /** New posting node the employee moves under. */
  toOrgNodeId: string
  /** Reporting manager before/after the transfer — '—' when there wasn't one. */
  fromManagerName: string
  toManagerName: string
  effectiveDate: string
  reason: string
  remarks: string
}

/** Acting or Additional charge — a position an employee holds beyond their
 *  substantive posting. `acting` is temporary (has an end date); `additional`
 *  is a concurrently-held posting. */
export interface Charge {
  id: string
  kind: 'acting' | 'additional'
  title: string
  /** Optional org node the charge is attached to. */
  orgNodeId: string | null
  startDate: string | null
  endDate: string | null
  reason: string
}

export interface Employee {
  id: string
  code: string
  name: string
  designation: string
  email: string
  phone: string
  /** Organization/company name — from a visiting card, when the contact
   *  isn't a direct government employee (e.g. a vendor or consultant). */
  company: string
  address: string
  website: string
  photoUrl: string | null
  orgNodeId: string
  managerId: string | null
  /** A vacant position is a real seat in the hierarchy with a title but no
   *  incumbent yet. It renders distinctly and can be filled later ("assign a
   *  person") without rebuilding the tree. */
  vacant: boolean
  /** Whether this person is tracked as a relationship contact. When false,
   *  the fields below are hidden in the UI but kept intact so re-enabling
   *  restores them. */
  connected: boolean
  relationshipStatus: RelationshipStatus
  relationshipQuality: RelationshipQuality
  relationshipType: string
  introducedBy: string
  /** Flagged as a high-priority / VIP contact. */
  importantContact: boolean
  /** A contact can have more than one preferred channel. */
  preferredComm: PreferredComm[]
  lastInteractionAt: string | null
  followUpDate: string | null
  notes: string
  /** Acting + additional charges this person concurrently holds. */
  charges: Charge[]
  /** User-uploaded visiting cards. Each card holds a front image/PDF and an
   *  optional back, stored as data URLs. A person can have several cards. */
  visitingCards: VisitingCardItem[]
  metadata: Record<string, string>
  status: Status
}

/** A single sales opportunity a department is pursuing or executing.
 *
 *  A first-class record with a real `departmentId` foreign key. It was
 *  previously JSON-serialized into the department node's `metadata.works`,
 *  which meant an opportunity could not be found without knowing its
 *  department and could not be aggregated without parsing every one. */
export interface Opportunity {
  id: string
  /** Owning department node. Real FK — was implicit containment. */
  departmentId: string
  /** Denormalized from the department for state-scoped queries and search.
   *  Kept in sync by `createOpportunity`; a department never changes state. */
  stateCode: number | null
  /** → `PipelineStageDef.key`. Open string, never a union. */
  stageKey: string
  /** ISO date the opportunity reached a closed stage; null while open. */
  closedOn: string | null

  opportunityName: string
  /** GEM bid number or tender ID, whichever applies. */
  gemTenderId: string
  /** ISO date (YYYY-MM-DD) the tender/GEM listing was published. */
  publishDate: string
  /** ISO date (YYYY-MM-DD) the bid is due. */
  submissionDate: string
  vertical: string
  /** One or more component/product-line tags. */
  component: string[]
  quantity: string
  /** ISO 4217 code the value/EMD amounts below are denominated in. */
  currency: string
  /** Raw number the user entered, scaled by `valueUnit`. */
  valueAmount: string
  valueUnit: string
  /** Whether the budget figure is confirmed. `''` = not yet answered. */
  budgetKnown: string
  emdAmount: string
  emdUnit: string
  /** AMNEX sales-team member's email who owns this opportunity.
   *
   *  TRANSITIONAL. Replaced by `OwnershipAssignment('opportunity', id)` in
   *  the Ownership phase, which deletes this field alongside a department's
   *  `metadata.salesGeo` and a contact's `metadata.relationshipOwner` — all
   *  three go together so there is never a period with two answers to "who
   *  owns this". Until then it remains the only owner record. */
  salesPersonEmail: string

  createdAt: string
  createdBy: string | null
}

/** Append-only log of an opportunity's stage transitions.
 *
 *  Exists so "what was the pipeline on 1 June?", stage velocity, and
 *  conversion rates are answerable. Stage history CANNOT be reconstructed
 *  after the fact, which is why this ships before any dashboard needs it.
 *  Rows are never updated or deleted while their opportunity exists. */
export interface OpportunityStageChange {
  id: string
  opportunityId: string
  /** null for the row recording an opportunity's creation. */
  fromStageKey: string | null
  toStageKey: string
  /** ISO date (YYYY-MM-DD). */
  changedAt: string
  changedBy: string | null
  note: string
}

/** A scheduled piece of follow-up work against any entity. Replaces the
 *  single `Employee.followUpDate` field, which could hold only one, could
 *  not be assigned, and could not be closed. */
export interface FollowUp {
  id: string
  entityType: string
  entityId: string
  /** → `SalesPerson.id`. Always null until the Roster phase creates them. */
  assigneeId: string | null
  dueDate: string
  status: 'open' | 'done' | 'cancelled'
  note: string
  createdAt: string
  createdBy: string | null
}

/** One visiting card: a required front and an optional back, each an image or
 *  PDF stored as a data URL with its original filename. */
export interface VisitingCardItem {
  id: string
  frontUrl: string
  frontName: string
  backUrl: string | null
  backName: string | null
}

/** One scalar field carried over from a merged-away duplicate onto the
 *  surviving record, kept for the merge's audit trail. `kept` records which
 *  side the final value came from — 'survivor' only appears here when the
 *  user explicitly re-picked their own existing value during conflict
 *  review (otherwise an unchanged field is never listed at all). */
export interface MergeFieldResolution {
  field: string
  kept: 'survivor' | 'duplicate'
  value: string
}

/** A permanent record of one duplicate-contact merge — the removed record's
 *  id no longer resolves to anything, so this is the only place its identity
 *  and what happened to it survive for later review. */
export interface MergeAuditRecord {
  id: string
  survivorId: string
  survivorName: string
  duplicateId: string
  duplicateName: string
  mergedAt: string
  fieldResolutions: MergeFieldResolution[]
  transferred: {
    timelineEvents: number
    transfers: number
    directReports: number
    departmentHeadships: number
    visitingCards: number
    charges: number
  }
}

export interface ExternalId {
  entityType: 'geo_node' | 'org_node' | 'employee'
  entityId: string
  system: string
  value: string
}

export interface SearchResult {
  /** Navigation discriminant only. 'node'/'employee' route via the existing
   *  ws.select() workspace-selection mechanism; 'other' routes via the
   *  owning category's `path()` instead (see search-categories.ts). Adding a
   *  new entity type never adds a new value here — it's 'other' unless it's
   *  literally backed by HierNode or Employee. */
  kind: 'node' | 'employee' | 'other'
  /** Open string key into SEARCH_CATEGORIES (search-categories.ts) — not a
   *  closed union, same "data not enum" convention as HierNode.typeKey. */
  category: string
  id: string
  title: string
  subtitle: string
  code: string | null
  domain: Domain | null
  stateCode: number | null
  /** Short reason the result matched, shown by natural-language search. */
  note?: string
  /** For a `kind: 'other'` result that isn't independently addressable — the
   *  HierNode id its `path()` should navigate to instead (e.g. a Work's
   *  owning department). Omitted for results that don't need it. */
  containerId?: string
}

export interface FieldDef {
  key: string
  label: string
  type: 'string' | 'text' | 'url' | 'email' | 'phone'
}

type SalesPersonStatus = 'active' | 'onLeave' | 'resigned' | 'inactive'

/** An AMNEX salesperson. Deliberately holds no designation, tier, or manager:
 *  those are time-bounded and live on `SalesPosting`, so a promotion or reorg
 *  is a new interval rather than an overwrite that destroys history.
 *  Spec §6.2. Photo/documents are `Attachment`s — never inline data URLs. */
export interface SalesPerson {
  id: string
  employeeCode: string
  name: string
  /** Unique — the join key for the email-keyed data that predates this table. */
  officialEmail: string
  personalEmail: string
  mobile: string
  altMobile: string
  joinedOn: string | null
  leftOn: string | null
  status: SalesPersonStatus
  /** Plain text, not rich HTML. */
  notes: string
  metadata: Record<string, string>
  createdAt: string
  createdBy: string | null
}

/** Half-open interval: `startDate` inclusive, `endDate` exclusive, null = current.
 *  `changeType` is DERIVED by comparing `SalesTierDef.rank` across the closing
 *  and opening posting, never typed by the user. Spec §6.3.
 *
 *  There is deliberately no `team`, `region`, or `salesNodeIds` here: team is
 *  derived from shared manager, and coverage is ownership of a coverage area.
 *  Storing placement here as well would recreate the two-sources-of-truth
 *  problem this design exists to remove. */
export interface SalesPosting {
  id: string
  salesPersonId: string
  /** Free text — the printed title. */
  designation: string
  tierKey: string
  managerId: string | null
  office: string
  startDate: string
  endDate: string | null
  changeType: 'initial' | 'promotion' | 'demotion' | 'lateralMove' | 'reorg' | 'correction'
  reason: string
  createdAt: string
  createdBy: string | null
}

/** A commercial customer/account. New in Phase 2 — no prior in-memory
 *  behavior existed for this entity. */
export interface Customer {
  id: string
  name: string
  organization: string
  address: string
  gst: string
  contactName: string
  contactEmail: string
  contactPhone: string
  notes: string
  createdAt: string
  updatedAt: string
}

/** Ownership and delegation as a half-open interval — spec §6.4.
 *
 *  Delegation is a different ROLE, not a transfer: during one, the owner's row
 *  stays open and a parallel `role: 'delegate'` row exists with an end date. On
 *  expiry the delegate row simply stops resolving and the owner shows again,
 *  because it never stopped being theirs. No scheduled job, no restoration
 *  logic, no state machine. */
export interface OwnershipAssignment {
  id: string
  /** Open string → OWNABLE_ENTITIES. Never a TS union. */
  entityType: string
  entityId: string
  salesPersonId: string
  /** 'owner' | 'delegate' today; 'collaborator' is a future addition. */
  role: string
  startDate: string
  /** Exclusive. Mandatory when `role === 'delegate'`. */
  endDate: string | null
  reason: 'initial' | 'transfer' | 'delegation' | 'reassignment' | 'correction'
  batchId: string | null
  note: string
  createdAt: string
  createdBy: string | null
}
