import { NODE_TYPE_MAP } from '../../src/lib/node-types'
import { uid } from '../../src/lib/utils'
import { insertStatement, sqlTextArray } from './sql-utils'
import indiaAdmin from '../../src/data/india-admin.json'
import subdistricts from '../../src/data/subdistricts.json'

interface IndiaAdminDistrict { dt_code: string; district: string }
interface IndiaAdminState { st_code: string; st_nm: string; districts: IndiaAdminDistrict[] }
interface Subdistrict { code: string; name: string; dtCode: string; stCode: number; villageCount: number }

function buildNodeTypesSection(): string {
  const rows = Object.values(NODE_TYPE_MAP).map((t) => [
    t.key, t.domain, t.label, t.icon, t.level,
  ])
  let sql = '-- node_types\n'
  sql += insertStatement('node_types', ['key', 'domain', 'label', 'icon', 'level'], rows)
  // child_keys needs the array literal helper, not the scalar insertStatement path.
  for (const t of Object.values(NODE_TYPE_MAP)) {
    sql += `update public.node_types set child_keys = ${sqlTextArray(t.childKeys)} where key = '${t.key}';\n`
  }
  return sql
}

function buildGeoNodesSection(): { sql: string; countryId: string; stateIdByCode: Map<number, string> } {
  const countryId = uid('geo')
  const stateIdByCode = new Map<number, string>()
  const districtIdByCode = new Map<string, string>()

  const nodeRows: (string | number | null)[][] = []
  nodeRows.push([countryId, null, 'country', null, 'India', null, null, 0])

  const admin = indiaAdmin as IndiaAdminState[]
  admin.forEach((state, stateIdx) => {
    const stateCode = Number(state.st_code)
    const stateId = uid('geo')
    stateIdByCode.set(stateCode, stateId)
    nodeRows.push([stateId, countryId, 'state', stateCode, state.st_nm, state.st_code, state.st_code, stateIdx])

    state.districts.forEach((district, districtIdx) => {
      const districtId = uid('geo')
      districtIdByCode.set(district.dt_code, districtId)
      nodeRows.push([districtId, stateId, 'district', stateCode, district.district, district.dt_code, district.dt_code, districtIdx])
    })
  })

  const subs = subdistricts as Subdistrict[]
  subs.forEach((sub, idx) => {
    const districtId = districtIdByCode.get(sub.dtCode)
    if (!districtId) return // subdistrict references a district not present in india-admin.json — skip, don't fabricate a parent
    const talukaId = uid('geo')
    nodeRows.push([talukaId, districtId, 'taluka', sub.stCode, sub.name, sub.code, sub.code, idx])
  })

  const columns = ['id', 'parent_id', 'type_key', 'state_code', 'name', 'code', 'lgd_code', 'sort_order']
  const sql = '-- geo_nodes: country + all real states/districts/talukas\n' + insertStatement('geo_nodes', columns, nodeRows)
  return { sql, countryId, stateIdByCode }
}

async function main() {
  let out = '-- Generated by scripts/seed/build-seed-sql.ts — do not hand-edit. Re-run `npm run seed:generate`.\n\n'
  out += buildNodeTypesSection()
  out += '\n'
  out += buildGeoNodesSection().sql
  process.stdout.write(out)
}

main()
