// Regenerates the policy block of "Access Matrix.dc.html" and the React module's generated files from the canonical workbook.
//   node scripts/access-matrix/build.cjs [workbook.xlsx] [design.dc.html]
// Fails (and writes nothing) if the workbook has any validation error.
const fs = require('fs')
const path = require('path')
const { parseWorkbook, toPolicy } = require('./policy.cjs')

const root = path.resolve(__dirname, '..', '..')
const workbook = path.resolve(process.argv[2] || path.join(root, 'GOMS_RBAC_FINAL_implementation_ready_v7.xlsx'))
const target = path.resolve(process.argv[3] || path.join(root, 'Access Matrix.dc.html'))
const BEGIN = '// <access-matrix:generated>'
const END = '// </access-matrix:generated>'

const { fields, errors } = parseWorkbook(workbook)
if (errors.length) {
  console.error(`Refusing to build: ${errors.length} workbook error(s)`)
  errors.slice(0, 30).forEach((e) => console.error(`  [${e.code}] ${e.ctx}: ${e.msg}`))
  process.exit(1)
}
const policy = toPolicy(fields, path.basename(workbook))
const engine = fs.readFileSync(path.join(__dirname, 'engine.cjs'), 'utf8').trimEnd()
const block = [
  BEGIN,
  `// Generated by scripts/access-matrix/build.cjs from ${policy.source} (sheet "${policy.sheet}"). Do not edit by hand.`,
  engine,
  'const POLICY = ' + JSON.stringify(policy) + ';',
  END,
].join('\n')

const html = fs.readFileSync(target, 'utf8')
const a = html.indexOf(BEGIN), b = html.indexOf(END)
if (a < 0 || b < a) { console.error('Generated-region markers not found in ' + target); process.exit(1) }
const out = html.slice(0, a) + block + html.slice(b + END.length)
fs.writeFileSync(target, out)

// The React app consumes the same policy and the same engine source (no hand-written copy of either).
const genDir = path.join(root, 'src', 'modules', 'admin-access', 'access-matrix', 'generated')
fs.mkdirSync(genDir, { recursive: true })
const banner = `// Generated by scripts/access-matrix/build.cjs from ${policy.source} (sheet "${policy.sheet}"). Do not edit by hand.${'\n'}`
const exportList = 'amDecodeCell, amCell, amEffective, amAccessForScope, amScopeLabel, amLabelToScopes, amLevelAllowed, AM_ALLOWED_LEVELS, AM_SCOPE_LABEL, AM_SCOPE_BY_LETTER'
fs.writeFileSync(path.join(genDir, 'policy.generated.ts'), banner + "import type { Policy } from '../policyTypes'\n\nexport const POLICY: Policy = " + JSON.stringify(policy) + '\n')
fs.writeFileSync(path.join(genDir, 'engine.generated.js'), '/* eslint-disable */\n' + banner + engine + '\nexport { ' + exportList + ' }\n')
fs.copyFileSync(path.join(__dirname, 'engine.d.ts'), path.join(genDir, 'engine.generated.d.ts'))
console.log(`Wrote ${path.basename(target)}: ${fields.length} fields, ${fields.length * policy.teams.length * 6} cells`)
